name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build patch file
        run: find -type f -not -path './.*' -not -name README.md -exec zip -D ../omori-v1.08.rga {} +

  release:
    needs: [build]
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Generate changelog
      run: echo "Latest version" > ${{ github.workspace }}-CHANGELOG.txt
    - name: Upload rga patch
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ${{ github.workspace }}-CHANGELOG.txt
        files: ../omori-v1.08.rga

  publish:
    name: Remove old releases
    needs: [release, build]
    runs-on: ubuntu-latest
    steps:
    - uses: eregon/keep-last-n-releases@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        n: 1
